### ISSUE TITLE
Gallery Feedback

### ISSUE THREAD

**Issue by delsonting** [precariostecnicos/Pushnews#1]
Your template submission has been approved and should be live in the Gallery soon. 

A recommendation is to use the [encodeUriComponent](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) function to URI Encode data.accountId on line 55 of template.tpl file. This will help sanitize user input for a url.

**Comment by luratic-devs** [comment]
This has now been fixed by commit 80701ada62f55cebd4924030b695b3ca81586766. Thanks for the feedback!
